# Import our helper functions
import builder_functions as bf
params = bf.input_logic(ARGUMENTS, "library")

# Create the environments
envs = bf.create_builders(params, "library")

SConscript('SConscript', exports = 'envs')
