Help("""
	Type:

	'scons program' to build the program
	'scons clean' to remove program files
""")

import os

KOS_BASE = os.environ.get('KOS_BASE')	#Kinda made redundant by the "Adding in KOS vars" line

TARGET = Dir('.').path.rsplit('/', 1)[1] + "Test"		#Executable name (First part gets the name of the parent dir)
BINS = TARGET + ".bin" + " 1st_read.bin"				#Binaries
SCRAMBLED = "1st_read.bin"								#Scrambled-file-name
KOS_ROMDISK_DIR = "romdisk"
OBJS = TARGET + ".o" + " " + KOS_ROMDISK_DIR + ".o"		#Objects
LIBS = "-lkmg -lkosutils"								#Libs used when making the .elf file

CFILES = ' '.join(map(str, Glob('*.c')))		#Convert from list to string

env_dreamcast = Environment(CPPPATH = ['.'], CC = 'kos-cc', CCFLAGS = os.environ.get('KOS_CFLAGS'))
env_dreamcast['ENV']['PATH'] = os.environ['PATH']	#Import PATH for us. This fixes the "Unable to find kos-cc" thing
													#You could just add "ENV = os.environ" to the constructor instead
env_dreamcast['ENV'].update({k: v for k, v in os.environ.items() if k.startswith('KOS_')})	#Adding in KOS vars

#Both methods should work
# if True:
	# env_dreamcast.Object(target = 'kmgTest.o', source = 'kmgTest.c')	#Command should work, but we get the 2nd arg issue again...
# else:
	# env_dreamcast.Command("kmgTest.o", "kmgTest.c","kos-cc $CCFLAGS -c $SOURCE -o $TARGET")	#Can't find first arg (-O2)

env_dreamcast.Object(target = 'kmgTest.o', source = 'kmgTest.c')
